util.AddNetworkString("gT_ActiveConsole");
util.AddNetworkString("gT_EndConsole");
util.AddNetworkString("gT_AddLine");
util.AddNetworkString("gT_EndTyping");
util.AddNetworkString("gT_RedDerm")
util.AddNetworkString("gT_SaveDerm")
util.AddNetworkString("gT_ListCommands")
util.AddNetworkString("gT_SendListCommands")
util.AddNetworkString("gT_SendListHelper")
util.AddNetworkString("gT_StartKeyType")
util.AddNetworkString("gT_ActiveKeyType")
util.AddNetworkString("gT_EndKeyType")
